theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
true-color = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]

[keys.insert.j]
k = "normal_mode"

[keys.normal.space]
q = ":quit"
w = ":write"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true
