# theme = "gruvbox_dark_hard"
theme = "hex_steel_custom"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
true-color = true

[editor.soft-wrap]
enable = true

[editor.gutters.line-numbers]
min-width = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]

[keys.insert]
A-c = "normal_mode"

[keys.normal.space]
q = ":quit"
w = ":write"
e = ":write-all"
c = ":buffer-close"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true
